// MUI configure
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

// Theme
import ThemeContext from "@/common/theme";
import theme from "@/common/theme";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AppRouterCacheProvider>
                    <ThemeContext theme={theme}>{children}</ThemeContext>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
